
#set page(
    paper: "a4",
    margin: (x: 2cm, y: 2cm),
    header: [
        #grid(
            columns: (1fr, 1fr),
            align(left)[#text(size: 8pt, fill: rgb("#64748b"))[AUTORESTOCK-V2 ENTERPRISE PROCUREMENT SYSTEM]],
            align(right)[#text(size: 8pt, fill: rgb("#64748b"))[Official Document]]
        )
        #line(length: 100%, stroke: 0.5pt + rgb("#e2e8f0"))
    ]
)
#set text(font: "Arial", size: 10pt, fill: rgb("#1e293b"))

// Header Section
#grid(
    columns: (2fr, 1fr),
    gutter: 10pt,
    [
        #text(size: 15pt, weight: "bold", fill: rgb("#0f172a"))[PT RETAIL LOGISTIK NUSANTARA] \
        #text(size: 8.5pt, fill: rgb("#475569"))[
            Gedung Logistik Sentral Lt. 4, Kawasan Industri Pulogadung \
            Jakarta Timur, DKI Jakarta 13920 | Telp: (021) 460-9988 \
            Email: procurement\@retail-nusantara.co.id
        ]
    ],
    align(right)[
        #rect(
            fill: rgb("#f8fafc"),
            stroke: 1pt + rgb("#cbd5e1"),
            radius: 4pt,
            inset: 8pt
        )[
            #text(size: 10pt, weight: "bold", fill: rgb("#0f172a"))[SURAT PERMINTAAN PEMBELIAN] \
            #text(size: 8pt, fill: rgb("#64748b"))[(PURCHASE REQUISITION)] \
            #v(2pt)
            #text(size: 9.5pt, weight: "bold", fill: rgb("#2563eb"))[PR-20260820-170553-01]
        ]
    ]
)

#v(8pt)
#line(length: 100%, stroke: 1.5pt + rgb("#0f172a"))
#v(6pt)

// Information Grid
#grid(
    columns: (1fr, 1fr),
    gutter: 14pt,
    [
        #block(
            fill: rgb("#f8fafc"),
            inset: 8pt,
            radius: 4pt,
            stroke: 0.5pt + rgb("#e2e8f0")
        )[
            #text(weight: "bold", size: 9pt)[INFORMASI DOKUMEN:] \
            #grid(
                columns: (85pt, 1fr),
                gutter: 4pt,
                [Tanggal Terbit:], [2026-08-20],
                [Prioritas / Urgensi:], [#text(weight: "bold", fill: rgb("#b45309"))[NORMAL]],
                [Status Dokumen:], [#text(weight: "bold", fill: rgb("#d97706"))[PENDING_APPROVAL]],
                [Otorisasi Sistem:], [Auto-Restock Agent V2]
            )
        ]
    ],
    [
        #block(
            fill: rgb("#f8fafc"),
            inset: 8pt,
            radius: 4pt,
            stroke: 0.5pt + rgb("#e2e8f0")
        )[
            #text(weight: "bold", size: 9pt)[TARGET SUPPLIER / VENDOR:] \
            #grid(
                columns: (80pt, 1fr),
                gutter: 4pt,
                [ID Vendor:], [SUP-002],
                [Nama Vendor:], [#text(weight: "bold")[PT Sumber Alfaria Distribusi]],
                [Alamat Kirim:], [Gudang Utama - Loading Dock 2],
                [Metode Bayar:], [Net 30 Days]
            )
        ]
    ]
)

#v(10pt)
#text(weight: "bold", size: 10pt)[RINCIAN BARANG / MATERIAL YANG DIPESAN:]
#v(4pt)

// Items Table
#table(
    columns: (24pt, 85pt, 1fr, 55pt, 75pt, 85pt),
    fill: (col, row) => if row == 0 { rgb("#f1f5f9") } else if calc.even(row) { rgb("#f8fafc") } else { rgb("#ffffff") },
    stroke: 0.5pt + rgb("#cbd5e1"),
    inset: (x: 6pt, y: 6pt),
    align: (col, row) => (
        if row == 0 { center + horizon }
        else if col == 0 { center + horizon }
        else if col == 3 or col == 4 or col == 5 { right + horizon }
        else { left + horizon }
    ),
    [*No*], [*SKU*], [*Deskripsi Item*], [*Jumlah*], [*Harga Satuan*], [*Total Harga*],
    
            [1],
            [FMCG-BERAS-01],
            [Beras Setra Ramos Premium 5 Kg],
            [76 sak],
            [Rp 80.000],
            [Rp 6.080.000],
            
            [2],
            [FMCG-MINYAK-01],
            [Minyak Goreng Bimoli Klasik 2 Liter Pouch],
            [112 pouch],
            [Rp 36.500],
            [Rp 4.088.000],
            
            [3],
            [FNB-AQUA-01],
            [Air Mineral Aqua Botol 600ml (Karton 24 btl)],
            [98 karton],
            [Rp 54.000],
            [Rp 5.292.000],
            
)

#v(6pt)

// Financial Summary
#align(right)[
    #block(width: 250pt)[
        #table(
            columns: (120pt, 1fr),
            stroke: none,
            inset: 3pt,
            align: (left, right),
            [Subtotal Rincian:], [Rp 15.460.000],
            [PPN 11% (Pajak Masukan):], [Rp 1.700.600],
            [#line(length: 100%, stroke: 0.5pt + rgb("#94a3b8"))], [#line(length: 100%, stroke: 0.5pt + rgb("#94a3b8"))],
            [#text(weight: "bold", size: 10.5pt)[TOTAL ESTIMASI:]], [#text(weight: "bold", size: 10.5pt, fill: rgb("#0f172a"))[Rp 17.160.600]]
        )
    ]
]

#v(8pt)

// Notes
#if "Generated by Autonomous Agent. Awaiting Manager review." != "" [
    #block(
        fill: rgb("#fffbeb"),
        inset: 7pt,
        radius: 4pt,
        stroke: 0.5pt + rgb("#fde68a")
    )[
        #text(weight: "bold", size: 8.5pt, fill: rgb("#92400e"))[Catatan / Instruksi Pengadaan:] \
        #text(size: 8pt, fill: rgb("#78350f"))[Generated by Autonomous Agent. Awaiting Manager review.]
    ]
]

#v(16pt)

// Signatures Block
#grid(
    columns: (1fr, 1fr, 1fr),
    gutter: 15pt,
    align: center,
    [
        #text(size: 8pt)[Dibuat Otomatis Oleh:] \
        #v(30pt)
        #text(weight: "bold", size: 8.5pt)[AutoRestock AI Agent] \
        #text(size: 7.5pt, fill: rgb("#64748b"))[Autonomous Inventory Engine]
    ],
    [
        #text(size: 8pt)[Diperiksa Oleh:] \
        #v(30pt)
        #text(weight: "bold", size: 8.5pt)[Koordinator Gudang] \
        #text(size: 7.5pt, fill: rgb("#64748b"))[Warehouse Operations]
    ],
    [
        #text(size: 8pt)[Disetujui Oleh:] \
        #v(30pt)
        #text(weight: "bold", size: 8.5pt)[Manager Pengadaan] \
        #text(size: 7.5pt, fill: rgb("#64748b"))[Procurement Dept.]
    ]
)
